name: motoreto

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: motoreto_user
      POSTGRES_PASSWORD: "M@nred17"
      POSTGRES_DB: motoreto
    ports:
      - "56432:5432"             
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U motoreto_user -d motoreto"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  presentation:
    build:
      context: .
      dockerfile: src/Presentation/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: motoreto:${APP_VERSION:-dev}
    container_name: motoreto-${APP_VERSION:-dev}
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: "http://+:80"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=motoreto;Username=motoreto_user;Password=M@nred17;Include Error Detail=true"
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:80"
    restart: unless-stopped

volumes:
  pgdata:
