//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladcherryShopping.TejaratConfirmService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GladcherryShopping.TejaratConfirmService.ClientConfirmWithAmountRequestData))]
    public partial class ClientConfirmRequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginAccountField;
        
        private long TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoginAccount {
            get {
                return this.LoginAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginAccountField, value) != true)) {
                    this.LoginAccountField = value;
                    this.RaisePropertyChanged("LoginAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Token {
            get {
                return this.TokenField;
            }
            set {
                if ((this.TokenField.Equals(value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmWithAmountRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    [System.SerializableAttribute()]
    public partial class ClientConfirmWithAmountRequestData : GladcherryShopping.TejaratConfirmService.ClientConfirmRequestData {
        
        private long OrderIdField;
        
        private long AmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmResponseData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GladcherryShopping.TejaratConfirmService.ClientConfirmResponseDataAddData))]
    public partial class ClientConfirmResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberMaskedField;
        
        private long RRNField;
        
        private long TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CardNumberMasked {
            get {
                return this.CardNumberMaskedField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberMaskedField, value) != true)) {
                    this.CardNumberMaskedField = value;
                    this.RaisePropertyChanged("CardNumberMasked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long RRN {
            get {
                return this.RRNField;
            }
            set {
                if ((this.RRNField.Equals(value) != true)) {
                    this.RRNField = value;
                    this.RaisePropertyChanged("RRN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long Token {
            get {
                return this.TokenField;
            }
            set {
                if ((this.TokenField.Equals(value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientConfirmResponseDataAddData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    [System.SerializableAttribute()]
    public partial class ClientConfirmResponseDataAddData : GladcherryShopping.TejaratConfirmService.ClientConfirmResponseData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AddData {
            get {
                return this.AddDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AddDataField, value) != true)) {
                    this.AddDataField = value;
                    this.RaisePropertyChanged("AddData");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", ConfigurationName="TejaratConfirmService.ConfirmServiceSoap")]
    public interface ConfirmServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestData from namespace https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPayment", ReplyAction="*")]
        GladcherryShopping.TejaratConfirmService.ConfirmPaymentResponse ConfirmPayment(GladcherryShopping.TejaratConfirmService.ConfirmPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratConfirmService.ConfirmPaymentResponse> ConfirmPaymentAsync(GladcherryShopping.TejaratConfirmService.ConfirmPaymentRequest request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPaymentWithA" +
            "ddData", ReplyAction="*")]
        GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataResponse ConfirmPaymentWithAddData(GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPaymentWithA" +
            "ddData", ReplyAction="*")]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataResponse> ConfirmPaymentWithAddDataAsync(GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataRequest request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPaymentWithA" +
            "mount", ReplyAction="*")]
        GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountResponse ConfirmPaymentWithAmount(GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService/ConfirmPaymentWithA" +
            "mount", ReplyAction="*")]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountResponse> ConfirmPaymentWithAmountAsync(GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPayment", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public GladcherryShopping.TejaratConfirmService.ConfirmPaymentRequestBody Body;
        
        public ConfirmPaymentRequest() {
        }
        
        public ConfirmPaymentRequest(GladcherryShopping.TejaratConfirmService.ConfirmPaymentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GladcherryShopping.TejaratConfirmService.ClientConfirmRequestData requestData;
        
        public ConfirmPaymentRequestBody() {
        }
        
        public ConfirmPaymentRequestBody(GladcherryShopping.TejaratConfirmService.ClientConfirmRequestData requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public GladcherryShopping.TejaratConfirmService.ConfirmPaymentResponseBody Body;
        
        public ConfirmPaymentResponse() {
        }
        
        public ConfirmPaymentResponse(GladcherryShopping.TejaratConfirmService.ConfirmPaymentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GladcherryShopping.TejaratConfirmService.ClientConfirmResponseData ConfirmPaymentResult;
        
        public ConfirmPaymentResponseBody() {
        }
        
        public ConfirmPaymentResponseBody(GladcherryShopping.TejaratConfirmService.ClientConfirmResponseData ConfirmPaymentResult) {
            this.ConfirmPaymentResult = ConfirmPaymentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAddDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAddData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataRequestBody Body;
        
        public ConfirmPaymentWithAddDataRequest() {
        }
        
        public ConfirmPaymentWithAddDataRequest(GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAddDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GladcherryShopping.TejaratConfirmService.ClientConfirmRequestData requestData;
        
        public ConfirmPaymentWithAddDataRequestBody() {
        }
        
        public ConfirmPaymentWithAddDataRequestBody(GladcherryShopping.TejaratConfirmService.ClientConfirmRequestData requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAddDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAddDataResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataResponseBody Body;
        
        public ConfirmPaymentWithAddDataResponse() {
        }
        
        public ConfirmPaymentWithAddDataResponse(GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAddDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GladcherryShopping.TejaratConfirmService.ClientConfirmResponseDataAddData ConfirmPaymentWithAddDataResult;
        
        public ConfirmPaymentWithAddDataResponseBody() {
        }
        
        public ConfirmPaymentWithAddDataResponseBody(GladcherryShopping.TejaratConfirmService.ClientConfirmResponseDataAddData ConfirmPaymentWithAddDataResult) {
            this.ConfirmPaymentWithAddDataResult = ConfirmPaymentWithAddDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAmountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAmount", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountRequestBody Body;
        
        public ConfirmPaymentWithAmountRequest() {
        }
        
        public ConfirmPaymentWithAmountRequest(GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAmountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GladcherryShopping.TejaratConfirmService.ClientConfirmWithAmountRequestData requestData;
        
        public ConfirmPaymentWithAmountRequestBody() {
        }
        
        public ConfirmPaymentWithAmountRequestBody(GladcherryShopping.TejaratConfirmService.ClientConfirmWithAmountRequestData requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmPaymentWithAmountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmPaymentWithAmountResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService", Order=0)]
        public GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountResponseBody Body;
        
        public ConfirmPaymentWithAmountResponse() {
        }
        
        public ConfirmPaymentWithAmountResponse(GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Confirm/ConfirmService")]
    public partial class ConfirmPaymentWithAmountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GladcherryShopping.TejaratConfirmService.ClientConfirmResponseData ConfirmPaymentWithAmountResult;
        
        public ConfirmPaymentWithAmountResponseBody() {
        }
        
        public ConfirmPaymentWithAmountResponseBody(GladcherryShopping.TejaratConfirmService.ClientConfirmResponseData ConfirmPaymentWithAmountResult) {
            this.ConfirmPaymentWithAmountResult = ConfirmPaymentWithAmountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConfirmServiceSoapChannel : GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfirmServiceSoapClient : System.ServiceModel.ClientBase<GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap>, GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap {
        
        public ConfirmServiceSoapClient() {
        }
        
        public ConfirmServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfirmServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfirmServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfirmServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GladcherryShopping.TejaratConfirmService.ConfirmPaymentResponse GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap.ConfirmPayment(GladcherryShopping.TejaratConfirmService.ConfirmPaymentRequest request) {
            return base.Channel.ConfirmPayment(request);
        }
        
        public GladcherryShopping.TejaratConfirmService.ClientConfirmResponseData ConfirmPayment(GladcherryShopping.TejaratConfirmService.ClientConfirmRequestData requestData) {
            GladcherryShopping.TejaratConfirmService.ConfirmPaymentRequest inValue = new GladcherryShopping.TejaratConfirmService.ConfirmPaymentRequest();
            inValue.Body = new GladcherryShopping.TejaratConfirmService.ConfirmPaymentRequestBody();
            inValue.Body.requestData = requestData;
            GladcherryShopping.TejaratConfirmService.ConfirmPaymentResponse retVal = ((GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap)(this)).ConfirmPayment(inValue);
            return retVal.Body.ConfirmPaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratConfirmService.ConfirmPaymentResponse> GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap.ConfirmPaymentAsync(GladcherryShopping.TejaratConfirmService.ConfirmPaymentRequest request) {
            return base.Channel.ConfirmPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<GladcherryShopping.TejaratConfirmService.ConfirmPaymentResponse> ConfirmPaymentAsync(GladcherryShopping.TejaratConfirmService.ClientConfirmRequestData requestData) {
            GladcherryShopping.TejaratConfirmService.ConfirmPaymentRequest inValue = new GladcherryShopping.TejaratConfirmService.ConfirmPaymentRequest();
            inValue.Body = new GladcherryShopping.TejaratConfirmService.ConfirmPaymentRequestBody();
            inValue.Body.requestData = requestData;
            return ((GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap)(this)).ConfirmPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataResponse GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap.ConfirmPaymentWithAddData(GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataRequest request) {
            return base.Channel.ConfirmPaymentWithAddData(request);
        }
        
        public GladcherryShopping.TejaratConfirmService.ClientConfirmResponseDataAddData ConfirmPaymentWithAddData(GladcherryShopping.TejaratConfirmService.ClientConfirmRequestData requestData) {
            GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataRequest inValue = new GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataRequest();
            inValue.Body = new GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataRequestBody();
            inValue.Body.requestData = requestData;
            GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataResponse retVal = ((GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap)(this)).ConfirmPaymentWithAddData(inValue);
            return retVal.Body.ConfirmPaymentWithAddDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataResponse> GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap.ConfirmPaymentWithAddDataAsync(GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataRequest request) {
            return base.Channel.ConfirmPaymentWithAddDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataResponse> ConfirmPaymentWithAddDataAsync(GladcherryShopping.TejaratConfirmService.ClientConfirmRequestData requestData) {
            GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataRequest inValue = new GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataRequest();
            inValue.Body = new GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAddDataRequestBody();
            inValue.Body.requestData = requestData;
            return ((GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap)(this)).ConfirmPaymentWithAddDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountResponse GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap.ConfirmPaymentWithAmount(GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountRequest request) {
            return base.Channel.ConfirmPaymentWithAmount(request);
        }
        
        public GladcherryShopping.TejaratConfirmService.ClientConfirmResponseData ConfirmPaymentWithAmount(GladcherryShopping.TejaratConfirmService.ClientConfirmWithAmountRequestData requestData) {
            GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountRequest inValue = new GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountRequest();
            inValue.Body = new GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountRequestBody();
            inValue.Body.requestData = requestData;
            GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountResponse retVal = ((GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap)(this)).ConfirmPaymentWithAmount(inValue);
            return retVal.Body.ConfirmPaymentWithAmountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountResponse> GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap.ConfirmPaymentWithAmountAsync(GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountRequest request) {
            return base.Channel.ConfirmPaymentWithAmountAsync(request);
        }
        
        public System.Threading.Tasks.Task<GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountResponse> ConfirmPaymentWithAmountAsync(GladcherryShopping.TejaratConfirmService.ClientConfirmWithAmountRequestData requestData) {
            GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountRequest inValue = new GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountRequest();
            inValue.Body = new GladcherryShopping.TejaratConfirmService.ConfirmPaymentWithAmountRequestBody();
            inValue.Body.requestData = requestData;
            return ((GladcherryShopping.TejaratConfirmService.ConfirmServiceSoap)(this)).ConfirmPaymentWithAmountAsync(inValue);
        }
    }
}
