//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GladcherryShopping.TejaratBillService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientPaymentRequestDataBase", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GladcherryShopping.TejaratBillService.ClientBillPaymentRequestData))]
    public partial class ClientPaymentRequestDataBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginAccountField;
        
        private long AmountField;
        
        private long OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallBackUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginatorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LoginAccount {
            get {
                return this.LoginAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginAccountField, value) != true)) {
                    this.LoginAccountField = value;
                    this.RaisePropertyChanged("LoginAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CallBackUrl {
            get {
                return this.CallBackUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CallBackUrlField, value) != true)) {
                    this.CallBackUrlField = value;
                    this.RaisePropertyChanged("CallBackUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AdditionalData {
            get {
                return this.AdditionalDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalDataField, value) != true)) {
                    this.AdditionalDataField = value;
                    this.RaisePropertyChanged("AdditionalData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Originator {
            get {
                return this.OriginatorField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginatorField, value) != true)) {
                    this.OriginatorField = value;
                    this.RaisePropertyChanged("Originator");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientBillPaymentRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    [System.SerializableAttribute()]
    public partial class ClientBillPaymentRequestData : GladcherryShopping.TejaratBillService.ClientPaymentRequestDataBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BillId {
            get {
                return this.BillIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BillIdField, value) != true)) {
                    this.BillIdField = value;
                    this.RaisePropertyChanged("BillId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PayId {
            get {
                return this.PayIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayIdField, value) != true)) {
                    this.PayIdField = value;
                    this.RaisePropertyChanged("PayId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientPaymentResponseDataBase", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GladcherryShopping.TejaratBillService.ClientBatchBillPaymentResponseDataItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GladcherryShopping.TejaratBillService.ClientBillPaymentResponseData))]
    public partial class ClientPaymentResponseDataBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        private short StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Token {
            get {
                return this.TokenField;
            }
            set {
                if ((this.TokenField.Equals(value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public short Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientBatchBillPaymentResponseDataItem", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    [System.SerializableAttribute()]
    public partial class ClientBatchBillPaymentResponseDataItem : GladcherryShopping.TejaratBillService.ClientPaymentResponseDataBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrganizationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayIdField;
        
        private long AmountField;
        
        private long OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginAccountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string OrganizationName {
            get {
                return this.OrganizationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationNameField, value) != true)) {
                    this.OrganizationNameField = value;
                    this.RaisePropertyChanged("OrganizationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BillId {
            get {
                return this.BillIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BillIdField, value) != true)) {
                    this.BillIdField = value;
                    this.RaisePropertyChanged("BillId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PayId {
            get {
                return this.PayIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayIdField, value) != true)) {
                    this.PayIdField = value;
                    this.RaisePropertyChanged("PayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LoginAccount {
            get {
                return this.LoginAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginAccountField, value) != true)) {
                    this.LoginAccountField = value;
                    this.RaisePropertyChanged("LoginAccount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientBillPaymentResponseData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    [System.SerializableAttribute()]
    public partial class ClientBillPaymentResponseData : GladcherryShopping.TejaratBillService.ClientPaymentResponseDataBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientBatchBillPaymentRequestData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    [System.SerializableAttribute()]
    public partial class ClientBatchBillPaymentRequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallBackUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GladcherryShopping.TejaratBillService.ClientBatchBillPaymentRequestDataItem[] BillItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CallBackUrl {
            get {
                return this.CallBackUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CallBackUrlField, value) != true)) {
                    this.CallBackUrlField = value;
                    this.RaisePropertyChanged("CallBackUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public GladcherryShopping.TejaratBillService.ClientBatchBillPaymentRequestDataItem[] BillItems {
            get {
                return this.BillItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.BillItemsField, value) != true)) {
                    this.BillItemsField = value;
                    this.RaisePropertyChanged("BillItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientBatchBillPaymentRequestDataItem", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    [System.SerializableAttribute()]
    public partial class ClientBatchBillPaymentRequestDataItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginAccountField;
        
        private long OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BillId {
            get {
                return this.BillIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BillIdField, value) != true)) {
                    this.BillIdField = value;
                    this.RaisePropertyChanged("BillId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PayId {
            get {
                return this.PayIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayIdField, value) != true)) {
                    this.PayIdField = value;
                    this.RaisePropertyChanged("PayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LoginAccount {
            get {
                return this.LoginAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginAccountField, value) != true)) {
                    this.LoginAccountField = value;
                    this.RaisePropertyChanged("LoginAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AdditionalData {
            get {
                return this.AdditionalDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalDataField, value) != true)) {
                    this.AdditionalDataField = value;
                    this.RaisePropertyChanged("AdditionalData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDataViewModelBase", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GladcherryShopping.TejaratBillService.ClientBatchBillPaymentResponseData))]
    public partial class ResponseDataViewModelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private short StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public short Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientBatchBillPaymentResponseData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    [System.SerializableAttribute()]
    public partial class ClientBatchBillPaymentResponseData : GladcherryShopping.TejaratBillService.ResponseDataViewModelBase {
        
        private long TotalAmountField;
        
        private long BatchTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GladcherryShopping.TejaratBillService.ClientBatchBillPaymentResponseDataItem[] BillItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((this.TotalAmountField.Equals(value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long BatchToken {
            get {
                return this.BatchTokenField;
            }
            set {
                if ((this.BatchTokenField.Equals(value) != true)) {
                    this.BatchTokenField = value;
                    this.RaisePropertyChanged("BatchToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public GladcherryShopping.TejaratBillService.ClientBatchBillPaymentResponseDataItem[] BillItems {
            get {
                return this.BillItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.BillItemsField, value) != true)) {
                    this.BillItemsField = value;
                    this.RaisePropertyChanged("BillItems");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientBatchBillPaymentInfoResponseData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    [System.SerializableAttribute()]
    public partial class ClientBatchBillPaymentInfoResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayIdField;
        
        private long AmountField;
        
        private long OrderIdField;
        
        private long TokenField;
        
        private long BatchTokenField;
        
        private System.DateTime RequestDateTimeField;
        
        private int TerminalNoField;
        
        private int StatusField;
        
        private long RRNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string billTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BillId {
            get {
                return this.BillIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BillIdField, value) != true)) {
                    this.BillIdField = value;
                    this.RaisePropertyChanged("BillId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PayId {
            get {
                return this.PayIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PayIdField, value) != true)) {
                    this.PayIdField = value;
                    this.RaisePropertyChanged("PayId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public long Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long Token {
            get {
                return this.TokenField;
            }
            set {
                if ((this.TokenField.Equals(value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long BatchToken {
            get {
                return this.BatchTokenField;
            }
            set {
                if ((this.BatchTokenField.Equals(value) != true)) {
                    this.BatchTokenField = value;
                    this.RaisePropertyChanged("BatchToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime RequestDateTime {
            get {
                return this.RequestDateTimeField;
            }
            set {
                if ((this.RequestDateTimeField.Equals(value) != true)) {
                    this.RequestDateTimeField = value;
                    this.RaisePropertyChanged("RequestDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int TerminalNo {
            get {
                return this.TerminalNoField;
            }
            set {
                if ((this.TerminalNoField.Equals(value) != true)) {
                    this.TerminalNoField = value;
                    this.RaisePropertyChanged("TerminalNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public long RRN {
            get {
                return this.RRNField;
            }
            set {
                if ((this.RRNField.Equals(value) != true)) {
                    this.RRNField = value;
                    this.RaisePropertyChanged("RRN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string billType {
            get {
                return this.billTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.billTypeField, value) != true)) {
                    this.billTypeField = value;
                    this.RaisePropertyChanged("billType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientBillInfoResponseData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    [System.SerializableAttribute()]
    public partial class ClientBillInfoResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UtilityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubUtilityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        private short StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusDescriptionField;
        
        private System.DateTime RequestDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BillType {
            get {
                return this.BillTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BillTypeField, value) != true)) {
                    this.BillTypeField = value;
                    this.RaisePropertyChanged("BillType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UtilityCode {
            get {
                return this.UtilityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UtilityCodeField, value) != true)) {
                    this.UtilityCodeField = value;
                    this.RaisePropertyChanged("UtilityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SubUtilityCode {
            get {
                return this.SubUtilityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubUtilityCodeField, value) != true)) {
                    this.SubUtilityCodeField = value;
                    this.RaisePropertyChanged("SubUtilityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public short Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string StatusDescription {
            get {
                return this.StatusDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusDescriptionField, value) != true)) {
                    this.StatusDescriptionField = value;
                    this.RaisePropertyChanged("StatusDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime RequestDateTime {
            get {
                return this.RequestDateTimeField;
            }
            set {
                if ((this.RequestDateTimeField.Equals(value) != true)) {
                    this.RequestDateTimeField = value;
                    this.RaisePropertyChanged("RequestDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService", ConfigurationName="TejaratBillService.BillServiceSoap")]
    public interface BillServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestData from namespace https://pec.Shaparak.ir/NewIPGServices/Bill/BillService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService/BillPaymentRequest", ReplyAction="*")]
        GladcherryShopping.TejaratBillService.BillPaymentRequestResponse BillPaymentRequest(GladcherryShopping.TejaratBillService.BillPaymentRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService/BillPaymentRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.BillPaymentRequestResponse> BillPaymentRequestAsync(GladcherryShopping.TejaratBillService.BillPaymentRequestRequest request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace https://pec.Shaparak.ir/NewIPGServices/Bill/BillService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService/BatchBillPaymentRequest", ReplyAction="*")]
        GladcherryShopping.TejaratBillService.BatchBillPaymentRequestResponse BatchBillPaymentRequest(GladcherryShopping.TejaratBillService.BatchBillPaymentRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService/BatchBillPaymentRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.BatchBillPaymentRequestResponse> BatchBillPaymentRequestAsync(GladcherryShopping.TejaratBillService.BatchBillPaymentRequestRequest request);
        
        // CODEGEN: Generating message contract since element name GetBatchBillInfoResult from namespace https://pec.Shaparak.ir/NewIPGServices/Bill/BillService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService/GetBatchBillInfo", ReplyAction="*")]
        GladcherryShopping.TejaratBillService.GetBatchBillInfoResponse GetBatchBillInfo(GladcherryShopping.TejaratBillService.GetBatchBillInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService/GetBatchBillInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.GetBatchBillInfoResponse> GetBatchBillInfoAsync(GladcherryShopping.TejaratBillService.GetBatchBillInfoRequest request);
        
        // CODEGEN: Generating message contract since element name billId from namespace https://pec.Shaparak.ir/NewIPGServices/Bill/BillService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService/GetBillInfo", ReplyAction="*")]
        GladcherryShopping.TejaratBillService.GetBillInfoResponse GetBillInfo(GladcherryShopping.TejaratBillService.GetBillInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService/GetBillInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.GetBillInfoResponse> GetBillInfoAsync(GladcherryShopping.TejaratBillService.GetBillInfoRequest request);
        
        // CODEGEN: Generating message contract since element name GetBillInfoDataResult from namespace https://pec.Shaparak.ir/NewIPGServices/Bill/BillService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService/GetBillInfoData", ReplyAction="*")]
        GladcherryShopping.TejaratBillService.GetBillInfoDataResponse GetBillInfoData(GladcherryShopping.TejaratBillService.GetBillInfoDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService/GetBillInfoData", ReplyAction="*")]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.GetBillInfoDataResponse> GetBillInfoDataAsync(GladcherryShopping.TejaratBillService.GetBillInfoDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BillPaymentRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BillPaymentRequest", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService", Order=0)]
        public GladcherryShopping.TejaratBillService.BillPaymentRequestRequestBody Body;
        
        public BillPaymentRequestRequest() {
        }
        
        public BillPaymentRequestRequest(GladcherryShopping.TejaratBillService.BillPaymentRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    public partial class BillPaymentRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GladcherryShopping.TejaratBillService.ClientBillPaymentRequestData requestData;
        
        public BillPaymentRequestRequestBody() {
        }
        
        public BillPaymentRequestRequestBody(GladcherryShopping.TejaratBillService.ClientBillPaymentRequestData requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BillPaymentRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BillPaymentRequestResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService", Order=0)]
        public GladcherryShopping.TejaratBillService.BillPaymentRequestResponseBody Body;
        
        public BillPaymentRequestResponse() {
        }
        
        public BillPaymentRequestResponse(GladcherryShopping.TejaratBillService.BillPaymentRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    public partial class BillPaymentRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GladcherryShopping.TejaratBillService.ClientBillPaymentResponseData BillPaymentRequestResult;
        
        public BillPaymentRequestResponseBody() {
        }
        
        public BillPaymentRequestResponseBody(GladcherryShopping.TejaratBillService.ClientBillPaymentResponseData BillPaymentRequestResult) {
            this.BillPaymentRequestResult = BillPaymentRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchBillPaymentRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchBillPaymentRequest", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService", Order=0)]
        public GladcherryShopping.TejaratBillService.BatchBillPaymentRequestRequestBody Body;
        
        public BatchBillPaymentRequestRequest() {
        }
        
        public BatchBillPaymentRequestRequest(GladcherryShopping.TejaratBillService.BatchBillPaymentRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    public partial class BatchBillPaymentRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GladcherryShopping.TejaratBillService.ClientBatchBillPaymentRequestData requestData;
        
        public BatchBillPaymentRequestRequestBody() {
        }
        
        public BatchBillPaymentRequestRequestBody(GladcherryShopping.TejaratBillService.ClientBatchBillPaymentRequestData requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BatchBillPaymentRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BatchBillPaymentRequestResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService", Order=0)]
        public GladcherryShopping.TejaratBillService.BatchBillPaymentRequestResponseBody Body;
        
        public BatchBillPaymentRequestResponse() {
        }
        
        public BatchBillPaymentRequestResponse(GladcherryShopping.TejaratBillService.BatchBillPaymentRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    public partial class BatchBillPaymentRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GladcherryShopping.TejaratBillService.ClientBatchBillPaymentResponseData BatchBillPaymentRequestResult;
        
        public BatchBillPaymentRequestResponseBody() {
        }
        
        public BatchBillPaymentRequestResponseBody(GladcherryShopping.TejaratBillService.ClientBatchBillPaymentResponseData BatchBillPaymentRequestResult) {
            this.BatchBillPaymentRequestResult = BatchBillPaymentRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBatchBillInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBatchBillInfo", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService", Order=0)]
        public GladcherryShopping.TejaratBillService.GetBatchBillInfoRequestBody Body;
        
        public GetBatchBillInfoRequest() {
        }
        
        public GetBatchBillInfoRequest(GladcherryShopping.TejaratBillService.GetBatchBillInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    public partial class GetBatchBillInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long batchToken;
        
        public GetBatchBillInfoRequestBody() {
        }
        
        public GetBatchBillInfoRequestBody(long batchToken) {
            this.batchToken = batchToken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBatchBillInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBatchBillInfoResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService", Order=0)]
        public GladcherryShopping.TejaratBillService.GetBatchBillInfoResponseBody Body;
        
        public GetBatchBillInfoResponse() {
        }
        
        public GetBatchBillInfoResponse(GladcherryShopping.TejaratBillService.GetBatchBillInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    public partial class GetBatchBillInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GladcherryShopping.TejaratBillService.ClientBatchBillPaymentInfoResponseData[] GetBatchBillInfoResult;
        
        public GetBatchBillInfoResponseBody() {
        }
        
        public GetBatchBillInfoResponseBody(GladcherryShopping.TejaratBillService.ClientBatchBillPaymentInfoResponseData[] GetBatchBillInfoResult) {
            this.GetBatchBillInfoResult = GetBatchBillInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBillInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBillInfo", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService", Order=0)]
        public GladcherryShopping.TejaratBillService.GetBillInfoRequestBody Body;
        
        public GetBillInfoRequest() {
        }
        
        public GetBillInfoRequest(GladcherryShopping.TejaratBillService.GetBillInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    public partial class GetBillInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string billId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string payId;
        
        public GetBillInfoRequestBody() {
        }
        
        public GetBillInfoRequestBody(string billId, string payId) {
            this.billId = billId;
            this.payId = payId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBillInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBillInfoResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService", Order=0)]
        public GladcherryShopping.TejaratBillService.GetBillInfoResponseBody Body;
        
        public GetBillInfoResponse() {
        }
        
        public GetBillInfoResponse(GladcherryShopping.TejaratBillService.GetBillInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    public partial class GetBillInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GladcherryShopping.TejaratBillService.ClientBillInfoResponseData GetBillInfoResult;
        
        public GetBillInfoResponseBody() {
        }
        
        public GetBillInfoResponseBody(GladcherryShopping.TejaratBillService.ClientBillInfoResponseData GetBillInfoResult) {
            this.GetBillInfoResult = GetBillInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBillInfoDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBillInfoData", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService", Order=0)]
        public GladcherryShopping.TejaratBillService.GetBillInfoDataRequestBody Body;
        
        public GetBillInfoDataRequest() {
        }
        
        public GetBillInfoDataRequest(GladcherryShopping.TejaratBillService.GetBillInfoDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    public partial class GetBillInfoDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long token;
        
        public GetBillInfoDataRequestBody() {
        }
        
        public GetBillInfoDataRequestBody(long token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBillInfoDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBillInfoDataResponse", Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService", Order=0)]
        public GladcherryShopping.TejaratBillService.GetBillInfoDataResponseBody Body;
        
        public GetBillInfoDataResponse() {
        }
        
        public GetBillInfoDataResponse(GladcherryShopping.TejaratBillService.GetBillInfoDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://pec.Shaparak.ir/NewIPGServices/Bill/BillService")]
    public partial class GetBillInfoDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public GladcherryShopping.TejaratBillService.ClientBillInfoResponseData GetBillInfoDataResult;
        
        public GetBillInfoDataResponseBody() {
        }
        
        public GetBillInfoDataResponseBody(GladcherryShopping.TejaratBillService.ClientBillInfoResponseData GetBillInfoDataResult) {
            this.GetBillInfoDataResult = GetBillInfoDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BillServiceSoapChannel : GladcherryShopping.TejaratBillService.BillServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillServiceSoapClient : System.ServiceModel.ClientBase<GladcherryShopping.TejaratBillService.BillServiceSoap>, GladcherryShopping.TejaratBillService.BillServiceSoap {
        
        public BillServiceSoapClient() {
        }
        
        public BillServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GladcherryShopping.TejaratBillService.BillPaymentRequestResponse GladcherryShopping.TejaratBillService.BillServiceSoap.BillPaymentRequest(GladcherryShopping.TejaratBillService.BillPaymentRequestRequest request) {
            return base.Channel.BillPaymentRequest(request);
        }
        
        public GladcherryShopping.TejaratBillService.ClientBillPaymentResponseData BillPaymentRequest(GladcherryShopping.TejaratBillService.ClientBillPaymentRequestData requestData) {
            GladcherryShopping.TejaratBillService.BillPaymentRequestRequest inValue = new GladcherryShopping.TejaratBillService.BillPaymentRequestRequest();
            inValue.Body = new GladcherryShopping.TejaratBillService.BillPaymentRequestRequestBody();
            inValue.Body.requestData = requestData;
            GladcherryShopping.TejaratBillService.BillPaymentRequestResponse retVal = ((GladcherryShopping.TejaratBillService.BillServiceSoap)(this)).BillPaymentRequest(inValue);
            return retVal.Body.BillPaymentRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.BillPaymentRequestResponse> GladcherryShopping.TejaratBillService.BillServiceSoap.BillPaymentRequestAsync(GladcherryShopping.TejaratBillService.BillPaymentRequestRequest request) {
            return base.Channel.BillPaymentRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.BillPaymentRequestResponse> BillPaymentRequestAsync(GladcherryShopping.TejaratBillService.ClientBillPaymentRequestData requestData) {
            GladcherryShopping.TejaratBillService.BillPaymentRequestRequest inValue = new GladcherryShopping.TejaratBillService.BillPaymentRequestRequest();
            inValue.Body = new GladcherryShopping.TejaratBillService.BillPaymentRequestRequestBody();
            inValue.Body.requestData = requestData;
            return ((GladcherryShopping.TejaratBillService.BillServiceSoap)(this)).BillPaymentRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GladcherryShopping.TejaratBillService.BatchBillPaymentRequestResponse GladcherryShopping.TejaratBillService.BillServiceSoap.BatchBillPaymentRequest(GladcherryShopping.TejaratBillService.BatchBillPaymentRequestRequest request) {
            return base.Channel.BatchBillPaymentRequest(request);
        }
        
        public GladcherryShopping.TejaratBillService.ClientBatchBillPaymentResponseData BatchBillPaymentRequest(GladcherryShopping.TejaratBillService.ClientBatchBillPaymentRequestData requestData) {
            GladcherryShopping.TejaratBillService.BatchBillPaymentRequestRequest inValue = new GladcherryShopping.TejaratBillService.BatchBillPaymentRequestRequest();
            inValue.Body = new GladcherryShopping.TejaratBillService.BatchBillPaymentRequestRequestBody();
            inValue.Body.requestData = requestData;
            GladcherryShopping.TejaratBillService.BatchBillPaymentRequestResponse retVal = ((GladcherryShopping.TejaratBillService.BillServiceSoap)(this)).BatchBillPaymentRequest(inValue);
            return retVal.Body.BatchBillPaymentRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.BatchBillPaymentRequestResponse> GladcherryShopping.TejaratBillService.BillServiceSoap.BatchBillPaymentRequestAsync(GladcherryShopping.TejaratBillService.BatchBillPaymentRequestRequest request) {
            return base.Channel.BatchBillPaymentRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.BatchBillPaymentRequestResponse> BatchBillPaymentRequestAsync(GladcherryShopping.TejaratBillService.ClientBatchBillPaymentRequestData requestData) {
            GladcherryShopping.TejaratBillService.BatchBillPaymentRequestRequest inValue = new GladcherryShopping.TejaratBillService.BatchBillPaymentRequestRequest();
            inValue.Body = new GladcherryShopping.TejaratBillService.BatchBillPaymentRequestRequestBody();
            inValue.Body.requestData = requestData;
            return ((GladcherryShopping.TejaratBillService.BillServiceSoap)(this)).BatchBillPaymentRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GladcherryShopping.TejaratBillService.GetBatchBillInfoResponse GladcherryShopping.TejaratBillService.BillServiceSoap.GetBatchBillInfo(GladcherryShopping.TejaratBillService.GetBatchBillInfoRequest request) {
            return base.Channel.GetBatchBillInfo(request);
        }
        
        public GladcherryShopping.TejaratBillService.ClientBatchBillPaymentInfoResponseData[] GetBatchBillInfo(long batchToken) {
            GladcherryShopping.TejaratBillService.GetBatchBillInfoRequest inValue = new GladcherryShopping.TejaratBillService.GetBatchBillInfoRequest();
            inValue.Body = new GladcherryShopping.TejaratBillService.GetBatchBillInfoRequestBody();
            inValue.Body.batchToken = batchToken;
            GladcherryShopping.TejaratBillService.GetBatchBillInfoResponse retVal = ((GladcherryShopping.TejaratBillService.BillServiceSoap)(this)).GetBatchBillInfo(inValue);
            return retVal.Body.GetBatchBillInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.GetBatchBillInfoResponse> GladcherryShopping.TejaratBillService.BillServiceSoap.GetBatchBillInfoAsync(GladcherryShopping.TejaratBillService.GetBatchBillInfoRequest request) {
            return base.Channel.GetBatchBillInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.GetBatchBillInfoResponse> GetBatchBillInfoAsync(long batchToken) {
            GladcherryShopping.TejaratBillService.GetBatchBillInfoRequest inValue = new GladcherryShopping.TejaratBillService.GetBatchBillInfoRequest();
            inValue.Body = new GladcherryShopping.TejaratBillService.GetBatchBillInfoRequestBody();
            inValue.Body.batchToken = batchToken;
            return ((GladcherryShopping.TejaratBillService.BillServiceSoap)(this)).GetBatchBillInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GladcherryShopping.TejaratBillService.GetBillInfoResponse GladcherryShopping.TejaratBillService.BillServiceSoap.GetBillInfo(GladcherryShopping.TejaratBillService.GetBillInfoRequest request) {
            return base.Channel.GetBillInfo(request);
        }
        
        public GladcherryShopping.TejaratBillService.ClientBillInfoResponseData GetBillInfo(string billId, string payId) {
            GladcherryShopping.TejaratBillService.GetBillInfoRequest inValue = new GladcherryShopping.TejaratBillService.GetBillInfoRequest();
            inValue.Body = new GladcherryShopping.TejaratBillService.GetBillInfoRequestBody();
            inValue.Body.billId = billId;
            inValue.Body.payId = payId;
            GladcherryShopping.TejaratBillService.GetBillInfoResponse retVal = ((GladcherryShopping.TejaratBillService.BillServiceSoap)(this)).GetBillInfo(inValue);
            return retVal.Body.GetBillInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.GetBillInfoResponse> GladcherryShopping.TejaratBillService.BillServiceSoap.GetBillInfoAsync(GladcherryShopping.TejaratBillService.GetBillInfoRequest request) {
            return base.Channel.GetBillInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.GetBillInfoResponse> GetBillInfoAsync(string billId, string payId) {
            GladcherryShopping.TejaratBillService.GetBillInfoRequest inValue = new GladcherryShopping.TejaratBillService.GetBillInfoRequest();
            inValue.Body = new GladcherryShopping.TejaratBillService.GetBillInfoRequestBody();
            inValue.Body.billId = billId;
            inValue.Body.payId = payId;
            return ((GladcherryShopping.TejaratBillService.BillServiceSoap)(this)).GetBillInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GladcherryShopping.TejaratBillService.GetBillInfoDataResponse GladcherryShopping.TejaratBillService.BillServiceSoap.GetBillInfoData(GladcherryShopping.TejaratBillService.GetBillInfoDataRequest request) {
            return base.Channel.GetBillInfoData(request);
        }
        
        public GladcherryShopping.TejaratBillService.ClientBillInfoResponseData GetBillInfoData(long token) {
            GladcherryShopping.TejaratBillService.GetBillInfoDataRequest inValue = new GladcherryShopping.TejaratBillService.GetBillInfoDataRequest();
            inValue.Body = new GladcherryShopping.TejaratBillService.GetBillInfoDataRequestBody();
            inValue.Body.token = token;
            GladcherryShopping.TejaratBillService.GetBillInfoDataResponse retVal = ((GladcherryShopping.TejaratBillService.BillServiceSoap)(this)).GetBillInfoData(inValue);
            return retVal.Body.GetBillInfoDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.GetBillInfoDataResponse> GladcherryShopping.TejaratBillService.BillServiceSoap.GetBillInfoDataAsync(GladcherryShopping.TejaratBillService.GetBillInfoDataRequest request) {
            return base.Channel.GetBillInfoDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<GladcherryShopping.TejaratBillService.GetBillInfoDataResponse> GetBillInfoDataAsync(long token) {
            GladcherryShopping.TejaratBillService.GetBillInfoDataRequest inValue = new GladcherryShopping.TejaratBillService.GetBillInfoDataRequest();
            inValue.Body = new GladcherryShopping.TejaratBillService.GetBillInfoDataRequestBody();
            inValue.Body.token = token;
            return ((GladcherryShopping.TejaratBillService.BillServiceSoap)(this)).GetBillInfoDataAsync(inValue);
        }
    }
}
